# Generated by Django 5.1.4 on 2025-01-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifikasi',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
