# Generated by Django 5.1.4 on 2025-01-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryitem_tipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='stok',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='tipe',
        ),
    ]
