# Generated by Django 5.1.4 on 2025-01-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Diterima'), ('rejected', 'Ditolak'), ('completed', 'Selesai')], default='pending', max_length=10),
        ),
    ]
